### ISSUE TITLE
inconsequential if statement  

### ISSUE THREAD

**Issue by EdoMor** [sebastianprobst/resonator_tools#4]
in circuit inside the get_delay function line 309 of the file there is an assignment to A2 `A2=0`
on line 307 of the same file there is the same assignment 
is that on purpose?
code:

> 	def get_delay(self,f_data,z_data,delay=None,ignoreslope=True,guess=True):
> 	
> 		maxval = np.max(np.absolute(z_data))
> 		z_data = z_data/maxval
> 		A1, A2, A3, A4, fr, Ql = self._fit_skewed_lorentzian(f_data,z_data)
> 		if ignoreslope==True:
> 			A2 = 0.
> 		else:
> 			A2 = 0.

**Comment by sebastianprobst** [comment]
The option ignoreslope should no longe been used. This was a quick fix to deactivate it. I should clean up the code at this position.
