### ISSUE TITLE
axisbg is deprecated in matplotlib 2.0+

### ISSUE THREAD

**Issue by JBraumueller** [sebastianprobst/resonator_tools#5]
An error is thrown in GUIfit with new versions of matplotlib. Maybe you can use facecolor instead.

**Comment by sebastianprobst** [comment]
Is this still an open issue? Can you provide a solution and send a pull request? Thanks.

**Comment by lukelbro** [comment]
This issue is still open - I created a pull request with the necessary changes.

**Comment by sebastianprobst** [comment]
Thank you for your contribution!

**Comment by sebastianprobst** [comment]
Changes merged with master.
