### ISSUE TITLE
Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'. Unable to do any autofitting, also with the examples

### ISSUE THREAD

**Issue by 4le91** [sebastianprobst/resonator_tools#6]
TypeError                                 Traceback (most recent call last)
<ipython-input-17-4e405012da29> in <module>
----> 1 port1.autofit()

~\Desktop\resonator_tools-master\resonator_tools\circuit.py in autofit(self, electric_delay, fcrop)
    162                         self._fid = np.logical_and(self.f_data>=f1,self.f_data<=f2)
    163                 delay, amp_norm, alpha, fr, Ql, A2, frcal =\
--> 164                                 self.do_calibration(self.f_data[self._fid],self.z_data_raw[self._fid],ignoreslope=True,guessdelay=False,fixed_delay=electric_delay)
    165                 self.z_data = self.do_normalization(self.f_data,self.z_data_raw,delay,amp_norm,alpha,A2,frcal)
    166                 self.fitresults = self.circlefit(self.f_data[self._fid],self.z_data[self._fid],fr,Ql,refine_results=False,calc_errors=True)

~\Desktop\resonator_tools-master\resonator_tools\circuit.py in do_calibration(self, f_data, z_data, ignoreslope, guessdelay, fixed_delay)
     88                 xc, yc, r0 = self._fit_circle(z_data)
     89                 zc = np.complex(xc,yc)
---> 90                 fitparams = self._phase_fit(f_data,self._center(z_data,zc),0.,np.absolute(params[5]),params[4])
     91                 theta, Ql, fr = fitparams
     92                 beta = self._periodic_boundary(theta+np.pi,np.pi) ###

~\Desktop\resonator_tools-master\resonator_tools\circlefit.py in _phase_fit(self, f_data, z_data, theta0, Ql, fr)
     70         Ql = p_final[0]
     71         p0 = [theta0, Ql, fr]
---> 72         p_final = spopt.leastsq(residuals_5,p0,args=(f_data,phase))
     73         return p_final[0]
     74 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\minpack.py in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
    392             maxfev = 200*(n + 1)
    393         retval = _minpack._lmdif(func, x0, args, full_output, ftol, xtol,
--> 394                                  gtol, maxfev, epsfcn, factor, diag)
    395     else:
    396         if col_deriv:

TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

​

**Comment by sebastianprobst** [comment]
solved
